experiment_name: "example_full_run"
seed: 2025
validation_split: 0.1
batch_size_train: 500
batch_size_test: 1000


preprocessing:
  # steps are (name, type, params)
  # runner will instantiate these via factory mapping (type -> class)
  steps:
    - name: "scaler"
      type: "StandardScaler"
      params: {}
    # - name: "pca"
    #  type: "IncrementalPCA"
    #  params:
    #    n_components: 7
  save_steps: true
  step_filename_template: "{name}.bin"

model:
  wrapper: "SKLearnClassifierWrapper"
  classifier_type: "SGDClassifier"
  classifier_params:
    loss: "hinge"
    penalty: "l2"
    random_state: 2025
  save_name: "classifier.bin"

commands:
  - name: "train_seq" # command name
    command: "train" # train/test
    mixer: # mixer = data selection strategy: sequence, balanced, random
      type: "sequence"
      # in sequence, drain all of the datasets to the end,
      # then begin with a new one
      datasets: ["001", "008", "010"]


  - name: "test_all"
    command: "test"
    mixer:
      type: "sequence"
      # in sequence, drain all of the datasets to the end,
      # then begin with a new one  BUT here TEST ALL
      datasets: ["001", "008", "009", "010"]
