experiment_name: lin_sequence_test

# root of the dataset folder
# should contain subfolders with ID in the names (e.g., 001, 002, ...)
root:
seed: 1111
validation_split: 0.1
batch_size_train: 500
batch_size_test: 1000

classes: ["Benign", "Malicious"]

# plotting scripts (paths are relative to the config file by default)
plotting_pths:
  training: "./src/plot_utils/plot_train_perf.py"
  testing: "./src/plot_utils/plot_test_perf.py"

paths:
  experiment_dir: ./experiments

dataset_loader:
  data_subdir: data
  persist_cache_threshold: 20000
  cache_dir: ./cache
  labeled_filenames:
    - conn.log.labeled
    - labeled-conn.log
    - conn.log
  file_encoding: utf-8
  file_errors: ignore
  shuffle_per_epoch: false

features:
  default_label: Benign
  protocols_to_discard:
    - arp
    - ARP
    - icmp
    - igmp
    - ipv6-icmp
    - ""

preprocessing:
  # steps are (name, type, params)
  # runner will instantiate these via factory mapping (type -> class)
  steps:
    - name: "scaler"
      type: "StandardScaler"
      params: {}
    # - name: "pca"
    #  type: "IncrementalPCA"
    #  params:
    #    n_components: 7
  save_steps: true
  step_filename_template: "{name}.bin"

  # model:
  #   wrapper: RiverClassifierWrapper
  #   classifier_type: ADWINBoostingClassifier
  #   classifier_params:
  #     n_models: 5
  #     model:
  #       type: HoeffdingAdaptiveTreeClassifier
  #       params:
  #         max_depth: 15
  #         grace_period: 300
  #         max_size: 10
  #         delta: 1.0e-7
  #   save_name: classifier_adwinboost.bin

model:
  wrapper: SklearnClassifierWrapper
  classifier_type: SGDClassifier
  classifier_params:
    loss: "hinge"
    class_weight:
      "Benign": 2
      "Malicious": 1
    alpha: 0.05

# model:
#   wrapper: RiverClassifierWrapper
#   classifier_type: ARFClassifier
#   classifier_params:
#     lambda_value: 10
#     n_models: 10

commands:
#  - name: "train_seq" # command name
#    command: "train" # train/test
#    mixer: #types: oversampling, balanced, random, sequence
#      type: sequence
#      datasets: ["010","015","011","010"]

  # - name: "train_balanced" # command name
  #   command: "train" # train/test
  #   mixer: #types: oversampling, balanced, random, sequence
  #     type: balanced
  #     # Label configuration
  #     labels: ["Benign", "Malicious"]

  #     # Balance specification (fractions must sum to 1.0)
  #     balance:
  #       Benign: 0.5
  #       Malicious: 0.5
  #     datasets: ["010","015","011","010"]

  - name: "sequential_train_fast" # command name
    command: "train" # train/test
    mixer:
      type: "sequence"
       # Label configuration
      labels: ["Benign", "Malicious"]

       # Balance specification (fractions must sum to 1.0)
      balance:
        Benign: 0.5
        Malicious: 0.5

      # Alternative balance formats (uncomment to use):
      # balance: [0.9, 0.1]  # List format (maps to labels in order)
      # balance: null  # Equal fractions for all labels


#     # Memory management
      stash_size_per_label: 800  # Default: 500,  samples for diversity
      buffer_size_per_label: 1500  # Default: 1000, unused samples queue

#     # Pull configuration
#     # Datasets to mix
      datasets: ["010", "011"]


  - name: "test_all"
    command: "test"
    mixer:
      type: "sequence"
      # in sequence, drain all of the datasets to the end,
      # then begin with a new one  BUT here TEST ALL
      datasets: ["001", "008", "009", "010", "011", "012",
                 "013", "014", "015", "016", "017", "018",
                 "020", "021", "025", "026", "030", "031",
                 "035", "036", "037"]
