import sys
import subprocess
from pathlib import Path
import numpy as np
import inspect


try:
    from src.conf_reader import ConfigReader
except Exception:
    from conf_reader import ConfigReader  # type: ignore


try:
    from src.class_factory import (
        get_transformer_class,
        get_classifier_class,
        get_wrapper_class,
        get_mixer_class,
        prepare_river_nested_model_params,
    )
except Exception:
    from class_factory import (
        get_transformer_class,
        get_classifier_class,
        get_wrapper_class,
        get_mixer_class,
        prepare_river_nested_model_params,
    )
try:
    from src.dataset_wrapper import find_and_load_datasets
except Exception:
    from dataset_wrapper import find_and_load_datasets

try:
    from src.features import FeatureExtraction
except Exception:
    from features import FeatureExtraction

try:
    from src.preprocessing_wrapper import PreprocessingWrapper
except Exception:
    from preprocessing_wrapper import PreprocessingWrapper

try:
    from src.logger import Logger
except Exception:
    from logger import Logger

try:
    from src.metrics_calculator import compute_binary_metrics
except Exception:
    from metrics_calculator import compute_binary_metrics

# -------------------------
# Experiment & Paths
# -------------------------
class ExperimentManager:
    def __init__(self, cfg_reader: ConfigReader):
        self.cfg_reader = cfg_reader
        self.cfg = cfg_reader.load()
        self.classes = cfg_reader.get_classes()
        # deterministic RNG for global usage
        self.rng = np.random.default_rng(int(cfg_reader.get_random_seed()))

        # resolved paths (cfg_reader guarantees experiment_dir_resolved)
        paths = self.cfg_reader.get_paths()
        self.expdir = Path(paths["experiment_dir_resolved"])

        # single output directory (contains logs, models, preprocessing, results)
        self.output_dir = self.expdir / "output"
        self.logs_dir = self.output_dir / "logs"
        self.models_dir = self.output_dir / "models"
        self.preprocessing_dir = self.output_dir / "preprocessing"
        self.results_dir = self.output_dir / "results"

        train_script, test_script = self.cfg_reader.get_plotting_paths()
        self.train_plotting_script = train_script
        self.test_plotting_script = test_script

    def prepare_dirs(self):
        # Only create output subdirectories, not the main experiment folder or config files
        for d in [self.output_dir, self.logs_dir, self.models_dir, self.preprocessing_dir, self.results_dir]:
            try:
                d.mkdir(parents=True, exist_ok=True)
            except Exception as e:
                print(f"[ERROR] Failed to create output subdirectory: {d}. Exception: {e}")
        # create readme if missing
        readme = self.expdir / "pipeline_run_log.txt"
        self.readme_path = readme
        if not readme.exists():
            try:
                readme.write_text(
                    f"Experiment: {self.cfg.get('experiment_name')}\nGenerated by PipelineRunner\n",
                    encoding="utf-8",
                )
            except Exception as e:
                print(f"[ERROR] Failed to create pipeline_run_log.txt: {readme}. Exception: {e}")
        if not self.output_dir.exists():
            print(f"[WARNING] Output directory was not created: {self.output_dir}")
        if not self.readme_path.exists():
            print(f"[WARNING] pipeline_run_log.txt was not created: {self.readme_path}")

    def validate_plotting_scripts(self):
        for script in (self.train_plotting_script, self.test_plotting_script):
            if not script or not Path(script).is_file():
                raise FileNotFoundError(f"Plotting script not found: {script}")
        self.train_plotting_script = str(Path(self.train_plotting_script).resolve())
        self.test_plotting_script = str(Path(self.test_plotting_script).resolve())

# -------------------------
# Single Build Manager (all builders combined)
# -------------------------
class BuildManager:
    """
    Single class to build loaders, feature extractor, preprocessor and classifier.
    Keeps construction logic in one place to reduce bloat.
    """
    def __init__(self, cfg_reader: ConfigReader, exp: ExperimentManager):
        self.cfg_reader = cfg_reader
        self.exp = exp
        self.loaders = None
        self.feature_extractor = None
        self.preprocessor = None
        self.classifier_wrapper = None

    def build_loaders(self):
        readme_path = self.exp.readme_path
        with open(readme_path, "a", encoding="utf-8") as readme_file:
            readme_file.write("Building dataset loaders...\n")
        ds = self.cfg_reader.get_dataset_loader_params()
        root = self.cfg_reader.load().get("root")
        if not root:
            raise ValueError("Config must define dataset root")
        self.loaders = find_and_load_datasets(
            root_dir=root,
            batch_size=int(ds.get("batch_size", 1000)),
            prefix_regex=ds.get("prefix_regex", r"^\d{3}"),
            data_subdir=ds.get("data_subdir", "data"),
            seed=int(self.cfg_reader.get_random_seed()),
        )
        return self.loaders

    def build_feature_extractor(self):
        readme_path = self.exp.readme_path
        with open(readme_path, "a", encoding="utf-8") as readme_file:
            readme_file.write("Building feature extractor...\n")
        params = self.cfg_reader.get_feature_extractor_params()
        self.feature_extractor = FeatureExtraction(**params)
        return self.feature_extractor

    def build_preprocessor(self):
        readme_path = self.exp.readme_path
        with open(readme_path, "a", encoding="utf-8") as readme_file:
            readme_file.write("Building preprocessor...\n")
        save_opts = self.cfg_reader.get_preprocessing_save_options()
        prep = PreprocessingWrapper(
            steps=[],
            experiment_name=self.cfg_reader.load().get("experiment_name"),
            base_models_dir=str(self.exp.preprocessing_dir),
            step_filename_template=save_opts.get("step_filename_template", "{name}.bin"),
        )
        for step in self.cfg_reader.get_preprocessing_steps():
            Cls = get_transformer_class(step["type"])
            prep.add_step(step.get("name"), Cls(**(step.get("params") or {})))

        load_from = (self.cfg_reader.load().get("preprocessing") or {}).get("load_from")
        if load_from:
            path = Path(load_from)
            if not path.is_absolute():
                path = self.exp.expdir / path
            prep.load(base_path=str(path))
        self.preprocessor = prep
        return self.preprocessor


    def build_classifier(self):
        spec = self.cfg_reader.get_model_spec()
        cls_type = spec.get("classifier_type") or spec.get("type")
        params = dict(spec.get("classifier_params", {}) or {})

        # Log building process to readme
        readme_path = self.exp.readme_path
        with open(readme_path, "a", encoding="utf-8") as readme_file:
            readme_file.write("Building classifier...\n")

        if "model" in params and isinstance(params["model"], dict):
            params = prepare_river_nested_model_params(params)

        Wrapper = get_wrapper_class(spec.get("wrapper", "SKLearnClassifierWrapper"))

        load_from = spec.get("load_from")
        load_name = spec.get("load_name", spec.get("save_name", "classifier.bin"))

        classifier_obj = None
        if cls_type:
            Cls = get_classifier_class(cls_type)

            seed = int(self.cfg_reader.get_random_seed())
            # Common randomness-related parameter names
            seed_keys = ["rng", "random", "seed", "random_seed", "state", "random_state"]
            try:
                sig = inspect.signature(Cls)
                for key in seed_keys:
                    if key in sig.parameters and key not in params:
                        params[key] = seed
            except Exception:
                # If signature inspection fails, skip injection
                pass
            try:
                classifier_obj = Cls(**params)
            except Exception as e:
                print(e)
                classifier_obj = None

        wrapper = Wrapper(
            classifier_obj,
            preprocessing_handler=self.preprocessor,
            classes=self.cfg_reader.get_classes(),
        )

        if load_from:
            path = Path(load_from)
            if not path.is_absolute():
                path = self.exp.expdir / path
            wrapper.load_classifier(str(path), name=load_name)

        self.classifier_wrapper = wrapper
        return self.classifier_wrapper

    def build_all(self):
        # build in sensible order
        loaders = self.build_loaders()
        feat = self.build_feature_extractor()
        prep = self.build_preprocessor()
        clf = self.build_classifier()
        return loaders, feat, prep, clf

# -------------------------
# Command executor
# -------------------------
class CommandExecutor:
    def __init__(self, cfg_reader: ConfigReader, exp: ExperimentManager, loaders, feature_extractor, preprocessor, classifier_wrapper):
        self.cfg_reader = cfg_reader
        self.exp = exp
        self.loaders = loaders
        self.feature_extractor = feature_extractor
        self.preprocessor = preprocessor
        self.classifier_wrapper = classifier_wrapper

    def _ensure_command_paths(self, cmd, idx):
        """
        Ensure each command has paths injected (strings) using output layout.
        All command artifacts will live under the single output directory.
        """
        cmd_paths = {
            "logs": str(self.exp.logs_dir.resolve()),
            "model": str(self.exp.models_dir.resolve()),
            "preprocessing": str(self.exp.preprocessing_dir.resolve()),
            "results": str(self.exp.results_dir.resolve()),
        }
        cmd["paths"] = cmd_paths

    def _prepare_mixer_spec(self, cmd):
        """Return a mixer_spec copy with effective validation split injected."""
        mixer_spec = dict(cmd.get("mixer", {}) or {})
        # prefer command-level computed effective validation split
        mixer_spec["validation_split"] = cmd.get(
            "effective_validation_split", mixer_spec.get("validation_split", 0.0)
        )
        # keep effective_batch_size available on command (mixers read effective_batch_size from cmd)
        mixer_spec["effective_batch_size"] = int(cmd.get("effective_batch_size"))
        return mixer_spec

    def _run_train(self, idx, cmd, val_metrics=None):
        readme_path = self.exp.readme_path
        with open(readme_path, "a", encoding="utf-8") as readme_file:
            readme_file.write(f"Running training command {cmd['name']}\n")
        mixer_spec = self._prepare_mixer_spec(cmd)
        mixer = get_mixer_class(mixer_spec["type"])(
            mixer_spec, self.loaders, self.exp.rng
        )
        mixer.reset_epoch(int(cmd["effective_batch_size"]), epoch_idx=0)

        logfile = Path(cmd["paths"]["logs"]) / f"{idx}_{cmd['name']}_train.log"
        logger = Logger(logfile_path=str(logfile), overwrite=True)

        while True:
            train_batch, val_batch = mixer.next_batch()
            if train_batch is None and val_batch is None:
                break  # end of epoch

            # ------------------ train
            X_train, y_train = self.feature_extractor.process_batch(train_batch)
            if X_train is None or len(X_train) == 0:
                continue

            # fit + transform ONLY on train
            self.preprocessor.partial_fit(X_train)
            X_train_p = self.preprocessor.transform(X_train)

            self.classifier_wrapper.partial_fit(X_train_p, np.asarray(y_train))
            y_pred_train = self.classifier_wrapper.predict(X_train_p)

            # ------------------ val
            y_pred_val = None
            y_val = None
            if val_batch is not None:
                X_val, y_val_tmp = self.feature_extractor.process_batch(val_batch)
                if X_val is not None and len(X_val) > 0:
                    # NO fitting here
                    X_val_p = self.preprocessor.transform(X_val)
                    y_pred_val = self.classifier_wrapper.predict(X_val_p)
                    y_val = np.asarray(y_val_tmp)


            batch_metrics = logger.save_training_results(
                y_pred_train=y_pred_train,
                y_gt_train=np.asarray(y_train),
                y_pred_val=y_pred_val,
                y_gt_val=y_val,
                sum_labeled_flows=len(y_train),
            )
            if val_metrics is not None and batch_metrics:
                metrics_val = batch_metrics.get("val")
                if metrics_val:
                    for key in ("TP", "FP", "FN", "TN"):
                        val_metrics[key] += int(metrics_val.get(key, 0))

        self.preprocessor.save(base_path=str(cmd["paths"]["preprocessing"]))
        self.classifier_wrapper.save_classifier(
            path=str(cmd["paths"]["model"]),
            name=self.cfg_reader.get_model_spec().get("save_name", "classifier.bin"),
        )

        with open(readme_path, "a", encoding="utf-8") as readme_file:
            readme_file.write(f"Successfully ending training command {cmd['name']}\n")


    def _run_test(self, idx, cmd, test_metrics=None):
        readme_path = self.exp.readme_path
        with open(readme_path, "a", encoding="utf-8") as readme_file:
            readme_file.write(f"Starting testing command {cmd['name']}\n")
        mixer_spec = self._prepare_mixer_spec(cmd)
        mixer = get_mixer_class(mixer_spec["type"])(mixer_spec, self.loaders, self.exp.rng)
        mixer.reset_epoch(int(cmd["effective_batch_size"]), epoch_idx=0)

        logfile = Path(cmd["paths"]["logs"]) / f"{idx}_{cmd['name']}_test.log"
        logger = Logger(logfile_path=str(logfile), overwrite=True)

        last_batch_metrics = None
        while True:
            batch, _ = mixer.next_batch()
            if batch is None:
                break

            X, y = self.feature_extractor.process_batch(batch)
            if X.shape[0] == 0:
                continue

            Xp = self.preprocessor.transform(X)
            y_pred = self.classifier_wrapper.predict(Xp)

            last_batch_metrics = logger.save_test_results(np.asarray(y), np.asarray(y_pred))

        self.preprocessor.save(base_path=str(cmd["paths"]["preprocessing"]))
        self.classifier_wrapper.save_classifier(
            path=str(cmd["paths"]["model"]),
            name=self.cfg_reader.get_model_spec().get("save_name", "classifier.bin"),
        )

        if test_metrics is not None and last_batch_metrics:
            for key in ("TP", "FP", "FN", "TN"):
                test_metrics[key] = int(last_batch_metrics.get(key, 0))


    def _run_command(self, idx, cmd):
        # ensure paths exist
        self._ensure_command_paths(cmd, idx)

        # run the actual command
        if cmd["command"] == "train":
            self._run_train(idx, cmd)
            script = self.exp.train_plotting_script
            log_file = self.exp.logs_dir / f"{idx}_{cmd['name']}_train.log"
        elif cmd["command"] == "test":
            self._run_test(idx, cmd)
            script = self.exp.test_plotting_script
            log_file = self.exp.logs_dir / f"{idx}_{cmd['name']}_test.log"
        else:
            raise ValueError(f"Unknown command '{cmd.get('command')}'")

        plot_evt = f"{idx}_{cmd['command']}"

        # run plotting script pointing directly to the log file
        readme_path = self.exp.readme_path
        with open(readme_path, "a", encoding="utf-8") as readme_file:
            readme_file.write("Starting plotting script in a subprocess\n")
        subprocess.run(
            [
                "python",
                script,
                "-f",
                str(log_file),  # point directly to the log
                "-e",
                plot_evt,
                "--save_folder",
                str(self.exp.results_dir),
            ],
            check=True,
        )



    def run_all(self):
        for idx, cmd in enumerate(self.cfg_reader.get_commands()):
            # ensure effective values are present (ConfigReader should have injected these)
            if "effective_batch_size" not in cmd or "effective_validation_split" not in cmd:
                raise RuntimeError(f"Command {idx} missing effective values: {cmd}")
            self._run_command(idx, cmd)

# -------------------------
# PipelineRunner entry point
# -------------------------
class PipelineRunner:
    def __init__(self, config_path_or_dir, optuna_mode=False, optuna_trial=None, optuna_dir=None):
        self.optuna_mode = optuna_mode
        self.optuna_trial = optuna_trial
        self.optuna_dir = optuna_dir
        self.cfg_reader = ConfigReader(config_path_or_dir)
        self.exp = ExperimentManager(self.cfg_reader)
        self.exp.prepare_dirs()
        self.exp.validate_plotting_scripts()
        bm = BuildManager(self.cfg_reader, self.exp)
        self.loaders, self.feature_extractor, self.preprocessor, self.classifier_wrapper = bm.build_all()

    def run(self):
        executor = CommandExecutor(
            self.cfg_reader,
            self.exp,
            self.loaders,
            self.feature_extractor,
            self.preprocessor,
            self.classifier_wrapper,
        )
        executor.run_all()
        return True

    def run_optuna_trial(self, optuna_trial=None, optuna_dir=None):
        commands = self.cfg_reader.get_commands()
        train_cmds = [c for c in commands if c.get("command") == "train"]
        if not train_cmds:
            raise RuntimeError("No train command found for Optuna trial.")
        metrics = {
            "f1": 0.0,
            "fpr": 1.0,
            "train_f1": 0.0,
            "train_fpr": 1.0,
            "test_f1": 0.0,
            "test_fpr": 1.0,
        }
        train_cmd = train_cmds[0]
        self.exp.prepare_dirs()
        self.exp.validate_plotting_scripts()
        bm = BuildManager(self.cfg_reader, self.exp)
        self.loaders, self.feature_extractor, self.preprocessor, self.classifier_wrapper = bm.build_all()
        executor = CommandExecutor(
            self.cfg_reader,
            self.exp,
            self.loaders,
            self.feature_extractor,
            self.preprocessor,
            self.classifier_wrapper,
        )

        train_idx = commands.index(train_cmd)
        executor._ensure_command_paths(train_cmd, train_idx)
        val_counts = {"TP": 0, "FP": 0, "FN": 0, "TN": 0}
        executor._run_train(train_idx, train_cmd, val_metrics=val_counts)
        train_total = sum(val_counts.values())
        if train_total == 0:
            train_f1 = 0.0
            train_fpr = 1.0
        else:
            train_metrics = compute_binary_metrics(val_counts)
            train_f1 = train_metrics.get("f1", 0.0)
            train_fpr = train_metrics.get("fpr", 0.0)
        metrics.update({
            "f1": train_f1,
            "fpr": train_fpr,
            "train_f1": train_f1,
            "train_fpr": train_fpr,
        })

        test_counts = None
        test_cmds = [c for c in commands if c.get("command") == "test"]
        if test_cmds:
            test_cmd = test_cmds[0]
            test_idx = commands.index(test_cmd)
            executor._ensure_command_paths(test_cmd, test_idx)
            test_counts = {"TP": 0, "FP": 0, "FN": 0, "TN": 0}
            executor._run_test(test_idx, test_cmd, test_metrics=test_counts)

        if test_counts is not None:
            test_total = sum(test_counts.values())
            if test_total == 0:
                test_f1 = 0.0
                test_fpr = 1.0
            else:
                test_metrics_bin = compute_binary_metrics(test_counts)
                test_f1 = test_metrics_bin.get("f1", 0.0)
                test_fpr = test_metrics_bin.get("fpr", 0.0)
            metrics.update({"test_f1": test_f1, "test_fpr": test_fpr})

        if optuna_dir is not None and optuna_trial is not None:
            trial_dir = Path(optuna_dir) / f"trial_{optuna_trial.number}"
            trial_dir.mkdir(parents=True, exist_ok=True)
            self.classifier_wrapper.save_classifier(path=str(trial_dir), name="model.bin")
            self.preprocessor.save(base_path=str(trial_dir))
        return metrics

# -------------------------
# CLI
# -------------------------
def _cli_main(argv=None):
    argv = argv or sys.argv
    runner = PipelineRunner(argv[1] if len(argv) > 1 else ".")
    runner.run()
    return 0

if __name__ == "__main__":
    sys.exit(_cli_main(sys.argv))
